name: Django CI (Custom Path)

on:
  push:
    branches: [ "main" ]

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install Linting Tools
      run: |
        pip install flake8
    - name: Lint
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
